*** Variables ***
${BASE_URL}                 https://www.digikala.com/
${PROFILE_BTN}              css=[data-cro-id="header-profile"]
${PROFILE_BTN2}             css=[data-cro-id="HP-profile-header"]
${LOGIN_REGISTER_BTN}       css=[data-cro-id="login-register"]
${USERNAME_INPUT}           name=username
${PASSWORD_INPUT}           name=password
${SUBMIT_BTN}               css=button[type="submit"]
${DIGIKALA_LOGO}            css=[data-cro-id="header-digikala-logo"]
${SEARCH_BUTTON}            css=[data-cro-id="searchbox-click"]
${SEARCH_INPUT}             css=[name="search-input"]
${PRODUCT_CARD_INDEX_1}     css=[data-product-index="1"]
${PRODUCT_BY_TITLE}         xpath=//*[text()='دوربین عکاسی چاپ سریع مدل DA3000']
${ADD_TO_CART_BTN}          xpath=//*[@data-testid="add-to-cart"]
${GO_TO_CART_LINK}          xpath=//a[@href="/checkout/cart/"]
${GO_TO_SHIPPING_LINK}      xpath=//a[@href="/checkout/shipping/"]
